data(iris)
dim(iris)
names(iris)
aggregate(Sepal.Length ~ Species, iris, mean)
aggregate(cbind(Petal.Length, Petal.Width) ~ Species, iris, function(x) c(mean(x), sd(x)))
library(ggplot2)
ggplot(iris, aes(x=Species, y=Sepal.Width)) + geom_boxplot()
cor(iris[, 1:4])
iris_sub <- subset(iris, Sepal.Length >= 5)
write.csv(iris_sub, "iris_sub.csv")
iris_sub2 <- read.csv("iris_sub.csv")